version: '3'
services:
  db:
     image: mysql
     container_name: mysql_db
     restart: always
     environment:
        - MYSQL_ROOT_PASSWORD="secret"
  web:
    image: tomcat
    depends_on:
       - db
    container_name: tomcat_web
    restart: always
    ports:
      - "80:8080"
  redis: 
    image: redis
    container_name : redis_cache
    restart : always
    ports: 
      - "6379:6379"